CREATE TABLE group_settings
(
    chat_id                BIGINT       NOT NULL PRIMARY KEY,
    chat_title             VARCHAR(256),
    gather_seconds         INT          NOT NULL,
    day_discussion_seconds INT          NOT NULL,
    day_vote_seconds       INT          NOT NULL,
    night_seconds          INT          NOT NULL,
    created_at             TIMESTAMP    NOT NULL,
    updated_at             TIMESTAMP    NOT NULL
);

CREATE TABLE group_disabled_role
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT      NOT NULL,
    role    VARCHAR(32) NOT NULL,
    CONSTRAINT uk_group_disabled_role UNIQUE (chat_id, role)
);

CREATE TABLE game
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id          BIGINT      NOT NULL,
    chat_title       VARCHAR(256),
    status           VARCHAR(16) NOT NULL,
    winner           VARCHAR(16),
    players_count    INT         NOT NULL,
    days_played      INT         NOT NULL,
    started_at       TIMESTAMP   NOT NULL,
    finished_at      TIMESTAMP,
    duration_seconds BIGINT
);

CREATE INDEX idx_game_chat_status ON game (chat_id, status);

CREATE TABLE game_player
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id      BIGINT       NOT NULL,
    chat_id      BIGINT       NOT NULL,
    user_id      BIGINT       NOT NULL,
    username     VARCHAR(128),
    display_name VARCHAR(256) NOT NULL,
    role         VARCHAR(32)  NOT NULL,
    faction      VARCHAR(16)  NOT NULL,
    survived     BOOLEAN      NOT NULL,
    winner       BOOLEAN      NOT NULL,
    death_day    INT,
    death_reason VARCHAR(32),
    CONSTRAINT fk_game_player_game FOREIGN KEY (game_id) REFERENCES game (id)
);

CREATE INDEX idx_game_player_chat_user ON game_player (chat_id, user_id);
CREATE INDEX idx_game_player_game ON game_player (game_id);

CREATE TABLE game_event
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id    BIGINT       NOT NULL,
    day_number INT          NOT NULL,
    phase      VARCHAR(32)  NOT NULL,
    event_type VARCHAR(64)  NOT NULL,
    details    VARCHAR(1024),
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_game_event_game FOREIGN KEY (game_id) REFERENCES game (id)
);

CREATE INDEX idx_game_event_game ON game_event (game_id);
